### ISSUE TITLE
Updated Version of Tagging Tool

### ISSUE THREAD

**Issue by Yer1k** [Yer1k/solar_wastewater#6]
I have updated the tagging tool so that the image displayed has the full image size.
Noticed while tagging that 500px may not be sufficient while tagging
Please review the new commit: [tagging_tool.py](https://github.com/Yer1k/solar_wastewater/blob/data/10_code/tools/tagging_tool.py)

e.g. Now it looks like this:
![image](https://github.com/Yer1k/solar_wastewater/assets/81750079/e4011d50-3d2a-4cbc-bc92-dc693187aadd)

**Comment by YZhu0225** [comment]
Enlarging image size helps for sure. 
Is the image a little too close to the choices? Can you change it to `"<style> img { max-width: 98%; height: auto; } </style>"` to add some margins?

**Comment by poojakabber7** [comment]
Do you want to try to center crop?

**Comment by Yer1k** [comment]
> Enlarging image size helps for sure. Is the image a little too close to the choices? Can you change it to `"<style> img { max-width: 98%; height: auto; } </style>"` to add some margins?

Yes, let me edit and try that.

**Comment by Yer1k** [comment]
> Do you want to try to center crop?

I wonder why would we want to do that. We did that for model training, but for actual tagging, I do not see the motivations here.

**Comment by Yer1k** [comment]
![image](https://github.com/Yer1k/solar_wastewater/assets/81750079/f03d7b8f-ab6b-4ec8-9f27-11012830bf0e)

Now it has been updated
